// Generated by CoffeeScript 1.7.1
(function() {
  var MyLogger, MyStringUtils, _, __myConsole, __myLog,
    __slice = [].slice;

  _ = require('underscore');

  __myConsole = console;

  MyStringUtils = require('./my_string_utils_step_2');

  __myLog = function(logLevel, args) {
    var messages, msg, _i, _len;
    messages = '';
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      msg = args[_i];
      messages += _.isString(msg) ? msg : JSON.stringify(msg, null, '\t') + ' ';
    }
    messages = MyStringUtils.getDateTimeStr(logLevel) + MyStringUtils.colorString(logLevel, messages);
    __myConsole[this.functionName[logLevel]](messages);
  };

  MyLogger = (function() {
    function MyLogger() {}

    MyLogger.functionName = {
      'log': 'log',
      'debug': 'info',
      'warn': 'warn',
      'error': 'error'
    };

    MyLogger.log = function() {
      var msgs;
      msgs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      __myLog.bind(this, 'log', msgs)();
    };

    MyLogger.debug = function() {
      var msgs;
      msgs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      __myLog.bind(this, 'debug', msgs)();
    };

    MyLogger.warn = function() {
      var msgs;
      msgs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      __myLog.bind(this, 'warn', msgs)();
    };

    MyLogger.error = function() {
      var msgs;
      msgs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      console.log(arguments.callee);
      __myLog.bind(this, 'error', msgs)();
    };

    return MyLogger;

  })();

  module.exports = MyLogger;

}).call(this);
